# Of course, you never really want to use `:latest`
Image: ghcr.io/llm-d-incubation/llm-d-fast-model-actuation-controller:latest

# Name of the ClusterRole to bind to controller to authorize it to
# get/list/watch Node objects.
# Empty string means no new binding is needed.
NodeViewClusterRole: ""

# Limit on the number of server-running Pods with a sleeping
# inference server, per GPU.
SleeperLimit: 2
