# Of course, you never really want to use `:latest`
Image: ghcr.io/llm-d-incubation/llm-d-fast-model-actuation/dual-pods-controller:latest

# Set this to true when deploying in a local cluster.
# This suppresses image pulls.
Local: false

# Name of the ClusterRole to bind to controller to authorize it to
# get/list/watch Node objects.
# Empty string means no new binding is needed.
NodeViewClusterRole: ""

# Limit on the number of server-running Pods with a sleeping
# inference server, per GPU.
SleeperLimit: 2

# Whether to debug the accelerator memory usage.
# This involves querying the requester;
# the test-requester does not support the query.
DebugAcceleratorMemory: true

# Whether to install validating admission policies and bindings
# from this chart. These policies prevent other parties from
# modifying labels and annotations that the FMA controllers rely upon.
# The chart will install them by default; set to false otherwise.
EnableValidationPolicy: true
