apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dual-pods
    app.kubernetes.io/component: controller
  name: "{{ .Release.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dual-pods
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dual-pods
        app.kubernetes.io/component: controller
    spec:
      containers:
      - name: controller
        image: {{ .Values.Image }}
        imagePullPolicy: Always
        command:
        - /ko-app/dual-pods-controller
        - "-v=5"
        - "--namespace=$(POD_NAMESPACE)"
        - "--sleeper-limit={{ .Values.SleeperLimit }}"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      serviceAccount: dual-pods-controller
