apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: dual-pods
    app.kubernetes.io/component: controller
  name: dual-pods-controller
rules:
- apiGroups: [ "fma.llm-d.ai" ]
  resources: [ inferenceserverconfigs, launcherconfigs ]
  verbs: [ get, list, watch ]
- apiGroups: [ "" ]
  resources: [ configmaps ]
  verbs: [ get, list, watch ]
- apiGroups: [ "" ]
  resources: [ pods ]
  verbs: [ get, list, watch, create, update, patch, delete ]
