apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: launcher-populator
    app.kubernetes.io/component: controller
  name: launcher-populator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: launcher-populator-role
subjects:
  - kind: ServiceAccount
    name: launcher-populator
    namespace: {{ .Values.namespace }}
{{if .Values.NodeViewClusterRole}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: launcher-populator
    app.kubernetes.io/component: controller
  name: launcher-populator-node-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Values.NodeViewClusterRole }}"
subjects:
  - kind: ServiceAccount
    namespace: "{{ .Release.Namespace }}"
    name: launcher-populator
{{end}}
