# Image configuration
image:
  repository: ghcr.io/llm-d-incubation/llm-d-fast-model-actuation-launcher-populator
  tag: latest
  pullPolicy: IfNotPresent

# Name of the ClusterRole to bind to controller to authorize it to
# get/list/watch Node objects.
# Empty string means no new binding is needed.
NodeViewClusterRole: ""

# Resource configuration
resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 128Mi
